Added support for single-end reads and added a new type of output to extract complete(r) MGE contigs

diff --git a/bin/xenoseq_functions b/bin/xenoseq_functions
--- a/bin/xenoseq_functions
+++ b/bin/xenoseq_functions
@@ -14,7 +14,6 @@ function parse_metadata() {
 	query_samples=()
 	reference_samples=()
 	output_dirs=()
-	# ancestral=$(cat $1 | cut -f2)
 	while read p; do
 		if [ ! ${p::1} == "#" ]; then
 			query=$(echo $p | cut -d ' ' -f1)
@@ -142,7 +141,7 @@ function unmapped_to_fasta() {
 # Function to check if previous command was succesful
 function success() {
 	if [ ! $1 -eq 0 ]; then
-  		echo -e "${RED}Error in xenoseq ($2). See relevant log files in ${output}/${sample}/logs (exit 1).${NC}" >&2
+  		echo -e "${RED}Error in xenoseq ($2). See relevant log files in ${output}/${sample%/}/logs (exit 1).${NC}" >&2
   		exit 1;
 	fi
 }
