Changed mincontig length for initial assembly to decrease fragmentation

diff --git a/bin/xenoseq_functions b/bin/xenoseq_functions
--- a/bin/xenoseq_functions
+++ b/bin/xenoseq_functions
@@ -130,12 +130,12 @@ function unmapped_to_fasta() {
 		echo -e "[xenoseq_find     $(date +%d-%m_%H:%M:%S)] Samtools: extracting non-hits "
 		samtools index $1
 		command="samtools view -f 4 $1"
-		$command > $output/${sample}/read_mapping/Unmapped_to_${2}.bam 2> ${output}/logs/samtools_filter.log
+		$command > $output/${sample}/read_mapping/Unmapped_to_${2}.bam 2> ${output}/${sample}/logs/samtools_filter.log
 		success $? "samtools filter"
 		if [ -f $output/${sample}/read_mapping/Unmapped_to_${2}.bam ]; then
 			command="samtools fasta $output/${sample}/read_mapping/Unmapped_to_${2}.bam"
-			$command > $output/${sample}/reads/unique_reads.fasta 2> ${output}/logs/samtools_fasta.log
-			success $? "samtools fasta"
+			$command > $output/${sample}/reads/unique_reads.fasta 2> ${output}/${sample}/logs/samtools_fasta.log
+			#success $? "samtools fasta"
 		else
 			echo -e "[xenoseq_find     $(date +%d-%m_%H:%M:%S)] Nothing unique found in ${sample} "
 		fi
@@ -145,7 +145,7 @@ function unmapped_to_fasta() {
 # Function to check if previous command was succesful
 function success() {
 	if [ ! $1 -eq 0 ]; then
-  		echo -e "${RED}Error in xenoseq ($2). See relevant log files in ${output}/logs (exit 1).${NC}" >&2
+  		echo -e "${RED}Error in xenoseq ($2). See relevant log files in ${output}/${sample}/logs (exit 1).${NC}" >&2
   		exit 1;
 	fi
 }
