Bugfixes 0.5.6

diff --git a/xenoseq b/xenoseq
--- a/xenoseq
+++ b/xenoseq
@@ -196,24 +196,26 @@ elif [[ $assembler == "spades" ]]; then
 		spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log 
 		fullspades=$?	
 		if [ $fullspades -gt 0 ]; then 
-			echo -en "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Spades failed using automatic kmer selection... :( ${NC}"
+			echo -e "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Spades failed using automatic kmer selection... :( ${NC}"
 			echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Assembling using Spades with lower smaller kmers... "
 			spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -k 21,33,55,77,99 -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log
 			halfspades=$?
 			if [ $halfspades -gt 0 ]; then 
-				echo -en "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Spades failed again with k-mers 21,33,55,77,99... trying MEGAHIT..."
+				echo -en "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Spades failed again with k-mers 21,33,55,77,99...${NC} trying MEGAHIT... "
 				megahit -r ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta -o ${dir}/${queryfilename_noext}_contigs 2> ${dir}/logs/megahit.log
 				megahit_return=$?
 				if [ $megahit_return -gt 0]; then					
-					echo -en "\n[xenoseq_main     $(date +%d-%m_%H:%M:%S)] Megahit failed. This is likely because there are no unique reads in your query at all. See ${BLUE}${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta${NC} for more info. (exit 1)"
+					echo -e "\n[xenoseq_main     $(date +%d-%m_%H:%M:%S)] ${RED}Even megahit failed.${NC} This is likely because there are almost no unique reads in your query at all. See ${BLUE}${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta${NC} for more info. (exit 1)"
 					exit 1;
 				else
-					echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Moving megahit contigs to output directory... "
+					echo -e "${GREEN}Done${NC}. (completed at $(date +%d-%m_%H:%M:%S))"
+					echo -e "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Moving megahit contigs to output directory... "
 					mv ${dir}/${queryfilename_noext}_contigs/final.contigs.fa ${dir}/unique_contigs.fasta
 				fi;
 			fi
 		fi;		
 		if [[ $fullspades == 0 || $halfspades == 0 ]]; then
+			echo -e "${GREEN}Done${NC}. (completed at $(date +%d-%m_%H:%M:%S))"
 			echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Moving contig-file to output directory... "
 			mv ${dir}/${queryfilename_noext}_contigs/contigs.fasta ${dir}/unique_contigs.fasta
 			echo -e "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${GREEN}Complete! Find your unique contigs in ${o}${NC}"
