Extra checkpoints for assembly fall-backs

diff --git a/xenoseq b/xenoseq
--- a/xenoseq
+++ b/xenoseq
@@ -15,6 +15,7 @@ version="0.5.4" # When re-running to the same output directory, it reuses old pr
 version="0.5.5" # Better error messages.
 version="0.5.6" # Fixed assembly fall-backs. 
 version="0.5.7" # Typo removed
+version="0.5.8" # Extra checkpoints for assembly fall-backs
 
 echo -e "\n${ORANGE} __    __                                                             ";
 echo "/  |  /  |                                                            ";
@@ -194,19 +195,31 @@ elif [[ $assembler == "spades" ]]; then
 	echo -e "[xenoseq_cmd     $(date +%d-%m_%H:%M:%S)] ${GREY}spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -o ${dir}/${queryfilename_noext}_contigs${NC}"
 	if [[ ! -f "${dir}/unique_contigs.fasta" ]]; then
 		echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Assembling using Spades... "
-		spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log 
-		fullspades=$?	
-		if [ $fullspades -gt 0 ]; then 
+		fullspades=1
+		if [[ ! -f "${dir}/intermediate_files/fullspades.tried" ]]; then
+			spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log 			
+			fullspades=$?
+		fi
+		if [ $fullspades -gt 0 ]; then 			
 			echo -e "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Spades failed using automatic kmer selection... :( ${NC}"
+			touch ${dir}/intermediate_files/fullspades.tried			
 			echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Assembling using Spades with smaller kmers... "
-			spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -k 21,33,55,77,99 -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log
-			halfspades=$?
+			halfspades=1
+			if [[ ! -f "${dir}/intermediate_files/halfspades.tried" ]]; then			
+				spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -k 21,33,55,77,99 -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log
+				halfspades=$?
+			fi
 			if [ $halfspades -gt 0 ]; then 
+				touch ${dir}/intermediate_files/halfspades.tried
 				echo -en "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Spades failed again with k-mers 21,33,55,77,99... :((${NC} trying MEGAHIT... "
-				megahit -r ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta -o ${dir}/${queryfilename_noext}_contigs 2> ${dir}/logs/megahit.log
-				megahit_return=$?
+				megahit_return=1
+				if [[ ! -f "${dir}/intermediate_files/megahit.tried" ]]; then
+					megahit -r ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta -o ${dir}/${queryfilename_noext}_contigs 2> ${dir}/logs/megahit.log
+					megahit_return=$?
+				fi
 				if [ $megahit_return -gt 0 ]; then					
-					echo -e "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Even megahit failed.${NC} This is likely because there are almost no unique reads in your query at all. See ${BLUE}${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta${NC} for more info. (exit 1)"
+					touch ${dir}/intermediate_files/megahit.tried
+					echo -e "\n[xenoseq_main    $(date +%d-%m_%H:%M:%S)] ${RED}Even megahit failed.${NC} This is likely because there are almost no unique reads in your query at all. Inspect your unique reads here: ${BLUE}${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta${NC}. (exit 1)"
 					exit 1;
 				else
 					echo -e "${GREEN}Done${NC}. (completed at $(date +%d-%m_%H:%M:%S))"
