Added an error-message for when spades fails due to low number of reads.

diff --git a/xenoseq b/xenoseq
--- a/xenoseq
+++ b/xenoseq
@@ -22,7 +22,6 @@ echo -e "                                                                  AA/ $
 echo -e "----------------------------------------------------------------------"
 echo -e "                          (XENOSEQ v0.5.2)                            "
 echo -e "----------------------------------------------------------------------\n"
-cores=4
 
 print_usage() {
 	echo -e "XENOSEQ v0.5.2\n"
@@ -159,10 +158,16 @@ if [[ $assembler == "megahit" ]]; then
 elif [[ $assembler == "spades" ]]; then
 	echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Assembling using Spades... "
 	spades.py -s ${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta --only-assembler -o ${dir}/${queryfilename_noext}_contigs &> ${dir}/logs/spades.log 
-	success $?
-	echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Moving contig-file to output directory... "
-	mv ${dir}/${queryfilename_noext}_contigs/contigs.fasta ${dir}/unique_contigs.fasta
-	success $?
+	fullspades = $?	
+	success fullspades
+	if [ fullspades -gt 0 ]; 
+		echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Spades failed using automatic kmer selection... :("
+		echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Try assembling ${BLUE}${dir}/intermediate_files/${queryfilename_noext}_uniq_reads.fasta${NC} with different kmers (spades option -k 21,33,55,77,99) or megahit"	
+	else
+		echo -en "[xenoseq_main    $(date +%d-%m_%H:%M:%S)] Moving contig-file to output directory... "
+		mv ${dir}/${queryfilename_noext}_contigs/contigs.fasta ${dir}/unique_contigs.fasta
+		success $?
+	fi;	
 else
 	echo -e "[xenoseq_main  $(date +%d-%m_%H:%M:%S)] ${RED}WARNING: assembler not recognised! (exit 1)${NC}"
 	exit 1;
